### PR TITLE
Port to jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
Requires a small rearrangement of files as jbuilder likes every library
to have its own directory.

The makefile here is only for convenience. Hopefully atdgen will now build on
windows too.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Note that jbuilder generates .merlin, .install, and META files. So I deleted all of those.

**Comment by mjambon** [comment]
Looking good. I'll give it a try before merging, tomorrow. Thanks for your patience.

**Comment by rgrinberg** [comment]
>Looking good. I'll give it a try before merging, tomorrow. Thanks for your patience.

No problem, take your time.

**Comment by mjambon** [comment]
Super impressive.

**Comment by mjambon** [comment]
I'm taking care of the opam release.

**Comment by mjambon** [comment]
https://github.com/ocaml/opam-repository/pull/9197

**Pull request merged**
